apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    tier: dev
spec:
  containers:
    - name: nginx-container
      image: nginx:1.18
      env:
      - name: DEMO_GREETING
        value: "HELLO from environment"
      - name: DEMO_FAREWELL
        value: "Such a Sweet sorryw"
